language: ruby

# sudo: required
sudo: false
dist: trusty
addons:
  chrome: stable

before_install:
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 about:blank &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache:
  bundler: true

matrix:
  fast_finish: true

  include:
    - gemfile: gemfiles/rails_4_2_opal_master.gemfile
      rvm: 2.3.7
    - gemfile: gemfiles/rails_5_0_opal_master.gemfile
      rvm: 2.4.4
    - gemfile: gemfiles/rails_5_1_opal_master.gemfile
      rvm: 2.5.1
    - gemfile: gemfiles/rails_5_2_opal_master.gemfile
      rvm: 2.5.1

    - gemfile: gemfiles/rails_4_2_opal_0_11.gemfile
      rvm: 2.3.7
    - gemfile: gemfiles/rails_5_0_opal_0_11.gemfile
      rvm: 2.4.4
    - gemfile: gemfiles/rails_5_1_opal_0_11.gemfile
      rvm: 2.5.1
    - gemfile: gemfiles/rails_5_2_opal_0_11.gemfile
      rvm: 2.5.1

  allow_failures:
    - gemfile: gemfiles/rails_4_2_opal_master.gemfile
      rvm: 2.3.7
    - gemfile: gemfiles/rails_5_0_opal_master.gemfile
      rvm: 2.4.4
    - gemfile: gemfiles/rails_5_1_opal_master.gemfile
      rvm: 2.5.1
    - gemfile: gemfiles/rails_5_2_opal_master.gemfile
      rvm: 2.5.1

before_script: bundle install
script: "bundle exec rake"


